name: lotus_lms_platform_frontend

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.5

# For UI and Auth packages
  flutter_secure_storage: ^5.0.2
  dio: ^5.0.4
  provider: ^6.0.3
  flutter_widgets: ^0.2.1